// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdakMVC.Data;

#nullable disable

namespace OdakMVC.Migrations
{
    [DbContext(typeof(OdakDbContext))]
    [Migration("20260330121421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdakMVC.Models.Entities.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Egitmen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Seviye")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.EkipUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Birim")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FotografYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gorev")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("EkipUyeleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Enes SELCUK",
                            Aktif = true,
                            Birim = "Yonetim",
                            Gorev = "Kulup Baskani",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Mustafa TUTAR",
                            Aktif = true,
                            Birim = "Yonetim",
                            Gorev = "Baskan Yardimcisi",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Yusuf EKINCI",
                            Aktif = true,
                            Birim = "Yonetim",
                            Gorev = "Genel Sekreter",
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Abdulkadir ELTER",
                            Aktif = true,
                            Birim = "Etkinlik Organizasyon",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 4
                        },
                        new
                        {
                            Id = 5,
                            AdSoyad = "Yusuf DEMIREL",
                            Aktif = true,
                            Birim = "Medya ve Iletisim",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 5
                        },
                        new
                        {
                            Id = 6,
                            AdSoyad = "Ali ERDINE",
                            Aktif = true,
                            Birim = "Etkinlik Organizasyon",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 6
                        },
                        new
                        {
                            Id = 7,
                            AdSoyad = "Ali EKBER",
                            Aktif = true,
                            Birim = "Egitim ve Yayin",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 7
                        },
                        new
                        {
                            Id = 8,
                            AdSoyad = "Muhammet Ali KOKYILDIRIM",
                            Aktif = true,
                            Birim = "Insan Kaynaklari",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 8
                        },
                        new
                        {
                            Id = 9,
                            AdSoyad = "Ishak ARIKAN",
                            Aktif = true,
                            Birim = "Medya ve Iletisim",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 9
                        },
                        new
                        {
                            Id = 10,
                            AdSoyad = "Ali KARA",
                            Aktif = true,
                            Birim = "Medya ve Iletisim",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 10
                        },
                        new
                        {
                            Id = 11,
                            AdSoyad = "Fatih Kaan KURT",
                            Aktif = true,
                            Birim = "Yonetim",
                            Gorev = "Yonetim Kurulu Uyesi",
                            Sira = 11
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfisGorseli")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Konum")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Saat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Etkinlikler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Odak Dusunce Kulubu olarak duzenledigimiz bu programda insan ve insan otesi kavramlari ele alinacak.",
                            AfisGorseli = "/gorseller/insan-programi/1.png",
                            Aktif = true,
                            Baslik = "Insan ve Insan Otesi Programi",
                            Konum = "Beyaz Bilgi Kitap Kahve",
                            OlusturulmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Saat = "19:30 - 21:30"
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.GaleriGorseli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EtkinlikAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GaleriGorselleri");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.IletisimMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.SliderGorseli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Siralama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SliderGorselleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/1.png",
                            Siralama = 1
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/2.png",
                            Siralama = 2
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/3.png",
                            Siralama = 3
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/4.png",
                            Siralama = 4
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Yayin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YayinTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Yayinlar");
                });
#pragma warning restore 612, 618
        }
    }
}
