// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdakMVC.Data;

#nullable disable

namespace OdakMVC.Migrations
{
    [DbContext(typeof(OdakDbContext))]
    [Migration("20260401180121_UpdateModels_Fixes")]
    partial class UpdateModels_Fixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdakMVC.Models.Entities.AdminKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("AdminKullanicilari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            KullaniciAdi = "admin",
                            Sifre = "Odak@2024!"
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Detay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Egitmen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Seviye")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.EkipBirimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EkipBirimleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Sosyal Medya, Tasarım",
                            Ad = "Medya ve İletişim",
                            Aktif = true,
                            Icon = "fas fa-bullhorn",
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Program Yönetimi, Organizasyon",
                            Ad = "Etkinlik Organizasyon",
                            Aktif = true,
                            Icon = "fas fa-calendar-check",
                            Sira = 2
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Ar-Ge, İçerik Üretimi",
                            Ad = "Eğitim ve Yayın",
                            Aktif = true,
                            Icon = "fas fa-book-reader",
                            Sira = 3
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Üye Kabul, İlişkiler",
                            Ad = "İnsan Kaynakları",
                            Aktif = true,
                            Icon = "fas fa-users-cog",
                            Sira = 4
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.EkipUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("EkipBirimiId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FotografYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gorev")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Hakkinda")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("HiyerarsiKademesi")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkipBirimiId");

                    b.ToTable("EkipUyeleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Enes SELÇUK",
                            Aktif = true,
                            Gorev = "Kulüp Başkanı",
                            HiyerarsiKademesi = 1,
                            Sira = 1
                        },
                        new
                        {
                            Id = 2,
                            AdSoyad = "Mustafa TUTAR",
                            Aktif = true,
                            Gorev = "Başkan Yardımcısı",
                            HiyerarsiKademesi = 2,
                            Sira = 1
                        },
                        new
                        {
                            Id = 3,
                            AdSoyad = "Yusuf EKİNCİ",
                            Aktif = true,
                            Gorev = "Genel Sekreter",
                            HiyerarsiKademesi = 2,
                            Sira = 2
                        },
                        new
                        {
                            Id = 4,
                            AdSoyad = "Abdulkadir ELTER",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 1
                        },
                        new
                        {
                            Id = 5,
                            AdSoyad = "Yusuf DEMİREL",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 2
                        },
                        new
                        {
                            Id = 6,
                            AdSoyad = "Ali ERDİNE",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 3
                        },
                        new
                        {
                            Id = 7,
                            AdSoyad = "Ali EKBER",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 4
                        },
                        new
                        {
                            Id = 8,
                            AdSoyad = "Muhammet Ali KÖKYILDIRIM",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 5
                        },
                        new
                        {
                            Id = 9,
                            AdSoyad = "İshak ARIKAN",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 6
                        },
                        new
                        {
                            Id = 10,
                            AdSoyad = "Ali KARA",
                            Aktif = true,
                            Gorev = "Yönetim Kurulu Üyesi",
                            HiyerarsiKademesi = 3,
                            Sira = 7
                        },
                        new
                        {
                            Id = 11,
                            AdSoyad = "Yusuf DEMİREL",
                            Aktif = true,
                            EkipBirimiId = 1,
                            Gorev = "Medya Sorumlusu",
                            HiyerarsiKademesi = 4,
                            Sira = 1
                        },
                        new
                        {
                            Id = 12,
                            AdSoyad = "Yusuf EKİNCİ",
                            Aktif = true,
                            EkipBirimiId = 2,
                            Gorev = "Program Koordinatörü",
                            HiyerarsiKademesi = 4,
                            Sira = 1
                        },
                        new
                        {
                            Id = 13,
                            AdSoyad = "Mustafa TUTAR",
                            Aktif = true,
                            EkipBirimiId = 3,
                            Gorev = "Ar-Ge",
                            HiyerarsiKademesi = 4,
                            Sira = 1
                        },
                        new
                        {
                            Id = 14,
                            AdSoyad = "Muhammet Ali KÖKYILDIRIM",
                            Aktif = true,
                            EkipBirimiId = 4,
                            Gorev = "İK Uzmanı",
                            HiyerarsiKademesi = 4,
                            Sira = 1
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AfisGorseli")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Konum")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Saat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Etkinlikler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Odak Dusunce Kulubu olarak duzenledigimiz programda insan...",
                            AfisGorseli = "/gorseller/insan-programi/1.png",
                            Aktif = true,
                            Baslik = "Insan ve Insan Otesi Programi",
                            Konum = "Beyaz Bilgi Kitap Kahve",
                            OlusturulmaTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Saat = "19:30 - 21:30"
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.GaleriGorseli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EtkinlikAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GaleriGorselleri");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.IcerikSayfasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anahtar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IcerikSayfalari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anahtar = "Hakkimizda",
                            Baslik = "Biz Kimiz?",
                            GorselYolu = "/gorseller/about.jpg",
                            Icerik = "Odak Düsünce Kulübü, 2024 yilinda bir grup idealist genç tarafindan kurulmus bir sivil toplum inisiyatifidir. Amacimiz, bilgi kirliliginin arttigi günümüzde, gençlerin dogru bilgiye ulasmasini saglamak ve onlari toplumsal meselelerde söz sahibi yapmaktir.\n\nOdak; yalnizca bilgi üretmeyi degil, anlam üretimini esas alir. Insanin kendini, çevresini ve dogayi tanima serüvenine eslik eden bu topluluk, ögrenmeyi bireysel bir süreçten çikarip kolektif bir anlam arayisina dönüstürmeyi hedefler."
                        },
                        new
                        {
                            Id = 2,
                            Anahtar = "Vizyon",
                            Baslik = "Vizyonumuz",
                            Icerik = "Okuyan, düsünen, arastiran ve kesfeden; zihinsel bagimsizligini kazanmis, toplumsal farkindaliga sahip bireylerden olusan güçlü bir sivil toplum inisiyatifi olmak."
                        },
                        new
                        {
                            Id = 3,
                            Anahtar = "Misyon",
                            Baslik = "Misyonumuz",
                            Icerik = "Gençlere dogru bilgiye ulasma, elestirel düsünme ve toplumsal meselelerde söz sahibi olma imkani sunmak; okuma, arastirma ve etkinliklerle kisisel ve toplumsal gelisime katkida bulunmak."
                        },
                        new
                        {
                            Id = 4,
                            Anahtar = "NedenOdak",
                            Baslik = "Neden ODAK?",
                            Icerik = "Çünkü her yolculuk bir arayisla baslar; biz de kendimizi, çevremizi ve çagimizi yeniden anlamak arzusuyla yola çiktik. Odak, kendini tanima ve içsel yolculuga çikma ihtiyacinin ortak bulusma noktasidir.\n\nDikkatimizi dagitan, bizi kendimizden uzaklastiran çeldiricilerin ortasinda, yeniden odaklanma çabamizin ifadesiyiz."
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.IletisimMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Okundu")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Kulup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KisaAciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("UzunAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kulupler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Oku",
                            Aktif = true,
                            Icon = "fas fa-book-open",
                            KisaAciklama = "Dünyayi ve insanligi anlamak için nitelikli kaynaklarla zihnimizi besliyoruz.",
                            Sira = 1,
                            UzunAciklama = "Oku kulübümüz, bilgiye ulasmanin degil, anlami kavramanin pesindedir. Her ay belirlenen kitaplarla zihinlerimizi besliyoruz."
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Düsün",
                            Aktif = true,
                            Icon = "fas fa-brain",
                            KisaAciklama = "Ezberleri bozuyor, elestirel düsünce ile olaylara farkli açilardan bakiyoruz.",
                            Sira = 2,
                            UzunAciklama = "Sorgulamadan kabul etme devrini kapatmak için bir araya geliyoruz. Felsefe, teoloji ve ideolojiler üzerine derin atölyeler yapiyoruz."
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Arastir",
                            Aktif = true,
                            Icon = "fas fa-microscope",
                            KisaAciklama = "Bilginin kaynagina iniyor, veriye dayali analizler yapiyoruz.",
                            Sira = 3,
                            UzunAciklama = "Bilimsel metodolojiler isiginda, toplumsal ve global olaylari inceliyor, raporluyoruz."
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kesfet",
                            Aktif = true,
                            Icon = "fas fa-compass",
                            KisaAciklama = "Ögrendiklerimizi hayata geçiriyor, yeni yetenekler ve dünyalar kesfediyoruz.",
                            Sira = 4,
                            UzunAciklama = "Sadece teoride kalmiyor. Sahada, müzelerde, köylerde geziyoruz. Yepyeni hobilerle becerilerimizi gelistiriyoruz."
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.SiteAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FaviconYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FooterAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LogoYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NSosyal")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SiteAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SiteBaslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Twitter")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WhatsAppNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Youtube")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adres = "Adana, Türkiye",
                            Email = "odakdusuncekulubu@gmail.com",
                            Facebook = "https://www.facebook.com/people/Odak-Kul%C3%BCb%C3%BC/pfbid0tw6mVHQTte16a38mhcEKpLSfLPZxk76HoAaC59HfS7mTmc8tefmSuUEAmfyNDbVwl/",
                            FaviconYolu = "/gorseller/OdakLogo.svg",
                            FooterAciklama = "Zihinsel gelişim ve toplumsal farkındalık için doğru odak noktasındasınız. Bizi takip etmeye devam edin.",
                            Instagram = "https://www.instagram.com/odakdusuncekulubu/",
                            LogoYolu = "/gorseller/OdakLogo.svg",
                            NSosyal = "https://nsosyal.com/odakdusuncekulubu",
                            SiteAciklama = "Odak Düşünce Kulübü; gençlerin zihinsel gelişimine katkıda bulunan okuma, düşünme, araştırma ve keşfetme odaklı bir sivil toplum inisiyatifidir.",
                            SiteBaslik = "Odak Düşünce Kulübü | Oku, Düşün, Araştır, Keşfet",
                            Telefon = "+90 552 272 25 63",
                            Twitter = "https://x.com/odakdusunceklb",
                            WhatsAppNo = "905522722563",
                            Youtube = "https://www.youtube.com/@odakdusuncekulubu"
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.SliderGorseli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Siralama")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SliderGorselleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/1.png",
                            Siralama = 1
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/2.png",
                            Siralama = 2
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/3.png",
                            Siralama = 3
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            GorselYolu = "/gorseller/sliders/4.png",
                            Siralama = 4
                        });
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.Yayin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DosyaYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GorselYolu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YayinTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Yayinlar");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.EkipUyesi", b =>
                {
                    b.HasOne("OdakMVC.Models.Entities.EkipBirimi", "EkipBirimi")
                        .WithMany("Uyeler")
                        .HasForeignKey("EkipBirimiId");

                    b.Navigation("EkipBirimi");
                });

            modelBuilder.Entity("OdakMVC.Models.Entities.EkipBirimi", b =>
                {
                    b.Navigation("Uyeler");
                });
#pragma warning restore 612, 618
        }
    }
}
